// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnuyqbaklozmqqzjqwns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudXlxYmFrbG96bXFxempxd25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzU0MDAsImV4cCI6MjA2NTQxMTQwMH0.9kzU2LjzkVOGrpPqP_MW7pNeLotQ1yAQtG6nVqiov1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);